config/routes.rb
Rails.application.routes.draw do

  get '/static_pages/FAQ'
  get 'people' => 'people#index'
  post 'people/filter' => 'people#filter'
  post 'users/filter' => 'users#filter'
  post 'teams/filter' => 'teams#filter'
  get 'sessions/new'
  get '/myteams' => 'teams#showbyuser'
  post 'messages' => 'messages#create'
  post 'messages/user' => 'messages#create_user_message'
  post 'addmember' => 'teams#add_user'

  resources :teams
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :teams
  has_many :user_messages

  include Filterable

  attr_accessor :remember_token

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  scope :user_name, -> (name) { where("lower(name) LIKE ?", "%#{name}%".downcase) }
  scope :summoner_name, -> (summoner_name) { where("lower(summoner_name) LIKE ?", "%#{summoner_name}%".downcase) }
  scope :server, -> (server) { where("lower(server) LIKE ?", "%#{server}%".downcase) }
  scope :level, -> (level) { where("lower(level) LIKE ?", "%#{level}%".downcase) }
  scope :sex, -> (sex) { where sex: sex }
  scope :voip, -> (voip) { where voip: voip }
  scope :hometown, -> (hometown) { where("lower(hometown) LIKE ?", "%#{hometown}%".downcase) }
  scope :country, -> (country) { where("lower(country) LIKE ?", "%#{country}%".downcase) }
  scope :division, -> (division) { where("lower(division) LIKE ?", "#{division}".downcase) }
  scope :level, -> (level) { where("lower(level) LIKE ?", "#{level}".downcase) }
  scope :league, -> (league) { where("lower(league) LIKE ?", "#{league}".downcase) }


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_token, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]


  def index
    @league = %w[Unranked Bronze Silver Gold Platinum Diamond Master Challenger]
    @divisions = %w[I II III IV V]
    @servers = %w[EUW EUN&E NA LAN LAS OCEANIA BRAZIL KOREA EUN JAPAN RUSSIA TURKEY ]
    @genders = %w[Male Female ]
    @voip = %w[Y N ]
    @users = User.all
  end

  def filter
    @users = User.filter(filter_params)
    render partial: 'shared/users'
    # render json: @users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Bienvenido a LOLPremade'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @messages = @user.user_messages
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params_edit)

      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end

  end

  private

    def filter_params
      params.require(:filter).permit(:user_name, :summoner_name, :league, :sex, :hometown, :country, :server, :age, :level, :division, :voip, :level)
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def user_params_edit
        params.require(:user).permit(:name, :password, :password_confirmation, :summoner_name, :image, :hometown, :country, :sex, :birthdate, :server, :league, :division, :level, :languages)
    end

    def logged_in_user
        unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
   end

   # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div id="users-filter-form">
        <%= form_for(:filter, url: users_filter_path, remote: true, html: { class: 'finding_back espaciado', id: 'users-filter' }) do |f| %>
        <fieldset class="">
            <div class="form-group list_color">
                <%= f.label :Nombre, class: 'control-label letra' %>
            <%= f.search_field :user_name, class: 'form-control  form-white-text', placeholder: 'nombre del usuario' %>
        </div>

        <div class="form-group list_color">
            <%= f.label :Nombre_Invocador, class: 'control-label' %>
            <%= f.search_field :summoner_name, class: 'form-control form-white-text', placeholder: 'nombre del invocador' %>
        </div>

        <div class="form-group list_color">
            <%= f.label :Liga, class: 'control-label' %>
            <%= f.select :league, @league, { include_blank: true } , class: 'form-control form-white-text' %>
        </div>

        <div class="form-group list_color">
            <%= f.label :Division, class: 'control-label' %>
            <%= f.select :division, @divisions, { include_blank: true }, { class: 'form-control form-white-text' }%>
        </div>

          <div class="form-group list_color">
              <%= f.label :Nivel, class: 'control-label' %>
            <%= f.search_field :level, class: 'form-control form-white-text', placeholder: 'nivel' %>
          </div>


          <div class="form-group list_color">
              <%= f.label :Ciudad, class: 'control-label' %>
            <%= f.search_field :hometown, class: 'form-control form-white-text', placeholder: 'ciudad de origen' %>
          </div>

          <div class="form-group list_color">
            <%= f.label :País, class: 'control-label' %>
            <%= f.search_field :country, class: 'form-control form-white-text', placeholder: 'pais' %>
          </div>

          <div class="form-group list_color">
              <%= f.label :Servidor, class: 'control-label' %>
            <%= f.select :server, @servers, { include_blank: true }, { class: 'form-control form-white-text' }%>
          </div>

          <div class="form-group list_color">
              <%= f.label :Género, class: 'control-label' %>
            <%= f.select :sex, @genders, { include_blank: true }, { class: 'form-control form-white-text' }%>
          </div>

          <div class="form-group list_color">
            <%= f.label :voip, class: 'control-label' %>
            <%= f.select :voip, @voip, { include_blank: true }, { class: 'form-control form-white-text' }%>
          </div>

        <div class="center-block">
            <%= f.submit 'Buscar', class: ' btn-lg myButton btn-block' %>
        </div>
        </fieldset>


    <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user, html: { class: '' }) do |f| %>

  <div class="fondo-entrada col-md-10 bordered">
    <div class="col-md-5  pull-left">

      <h1 class=" title Negrita">PERFIL</h1>
      <%= render 'shared/error_messages' %>

      <div class="form-group list_color">
          <%= f.label :Nombre %>
          <%= f.text_field :name, class: 'form-control form-white-text', placeholder: 'Nombre' %>
      </div>

      <div class="form-group list_color">
          <%= f.label :Imagen %>
        <%= f.select :image, [ 'corazon.png', 'osito.png', 'osito2.png', 'avatar1.jpg']%>
      </div>

      <div class="form-group list_color">
          <%= f.label :Ciudad %>
          <%= f.text_field :hometown, class: 'form-control form-white-text', placeholder: 'Ciudad' %>
      </div>

      <div class="form-group list_color">
        <%= f.label :Pais %>
        <%= f.text_field :country, class: 'form-control form-white-text', placeholder: 'Pais' %>
      </div>

      <div class="form-group">
          <%= f.label :Genero %>
        <div class="radio-edit form-white-text">
          
            <%= f.radio_button :sex, 'Male', {class: "form-white-text"}%> Male
          <%= f.radio_button :sex, 'Female', {class: "form-white-text"}%> Female
        </div>

      </div>

      <div class="form-group">
          <%= f.label :Fecha_Nacimiento %>
        <%= f.date_select :birthdate, class: 'form-control', placeholder: 'Birthdate', start_year: Date.today.year - 5, end_year: Date.today.year - 80 %>
      </div>

      <div class="form-group list_color">
          <%= f.label :Idiomas %>
          <%= f.text_field :languages, class: 'form-control form-white-text', placeholder: 'Idiomas' %>
      </div>
        

    </div>
      <div class="col-md-5 pull-right">

      <h1 class=" title Negrita">CUENTA</h1>
      <%= render 'shared/error_messages' %>

      <div class="form-group list_color">
          <%= f.label :Nombre_Invocador %>
          <%= f.text_field :summoner_name, class: 'form-control form-white-text', placeholder: 'Nombre de invocador'%>

        <div class="form-group ">
            <%= f.label :Servidor %>
        <%= f.select :server, ['EUW', 'EUN&E', 'NA', 'LAN', 'LAS', 'OCEANIA', 'BRAZIL', 'KOREA', 'EUN', 'JAPAN', 'RUSSIA', 'TURKEY' ]%>
      </div>


      <div class="form-group">
        <%= f.label :Liga %>
        <%= f.select :league, [ 'Unranked', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Master', 'Challenger']%>
      </div>


      <div class="form-group">
        <%= f.label :division %>
        <%= f.select :division, ['I', 'II', 'III', 'IV', 'V']%>
      </div>

      <div class="form-group">
          <%= f.label :Nivel %>
        <%= f.select :level,  1..30%>   </div>

      </div>
    </div>
  <div class="text-center columna-edit-boton">
      <%= f.submit "Guardar Cambios", class:'btn-lg myButton' %>
  </div>
</div>

<% end %>

app/views/users/index.html.erb
<div class="container-fluid">

    <%= render 'form' %>

    <%= render 'shared/users' %>
</div>

app/views/users/new.html.erb
<div class="register-page">
  <%= form_for(@user, html: { class: 'center-block lol-form' }) do |f| %>
    <h1 class="text-center">Registrate</h1>
    <%= render 'shared/error_messages' %>
    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Contraseña' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation,
                           class: 'form-control',
                           placeholder: 'Repite la contraseña' %>
    </div>

    <div class="text-center">
      <%= f.submit "Crear mi cuenta", class:'btn-lg myButton' %>
    </div>
  <% end %>

  <div id="enter-link" class="text-center">
      <p>Ya tienes usuario? <%= link_to 'Entra', sessions_new_path, {:class=> "enlace"} %></p>
      
</div>
</div>

app/views/users/show.html.erb
<div id="user-show" class="container-fluid">
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-2">
        <% if @user.image.nil? or @user.image == "" %>
            <img src="http://www.cultura-sorda.org/wp-content/uploads/2015/02/Usuario-Vacio1-300x300.png" class="imagen_user"/>
        <% else %>
          <%= image_tag "#{@user.image}", class:"imagen_user"%>
        <% end %>
      </div>
      <div class="col-md-6">
        <h1><%= @user.name.capitalize %></h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        
          <% if @user.league != nil && @user.league != "Unranked"%>
            <h2> <%= image_tag "#{@user.league.downcase}.png", size: '60x36' %>
            <%= @user.league %> - <%= @user.division %></h2>
          <% end %>
          <% if  @user.league.nil? || @user.league == "" || @user.league == "Unranked"%>
              <h2><span class="glyphicon glyphicon-king"></span> <%= @user.league %></h2>
          <% end %> 


        <div>Summoner Name: <%= @user.summoner_name %></div>
        <div>Server: <%=@user.server%></div>
        <div>Level: <%=@user.level%></div>

        <div>Teams:
            <% @user.teams.each do | team |%>
            <li class="margen-left"> <%= link_to team.teamname, team ,{:class=> "title"}%></li>
            <%end%>
        </div>

        <div>Sex: <%=@user.sex%></div>
        <div>Birthdate: <%=@user.birthdate%></div>
        <div>From:  <%= @user.hometown %>, <%= @user.country %></div>
        <div>Languages: <%=@user.languages%></div>


        <div class="margen-top">
          <% if logged_in? %>
            <span class="glyphicon glyphicon-envelope"></span>Enviar mensaje<br/>
            <span class="glyphicon glyphicon-plus"></span>Enviar invitación de equipo
          <% end %>
        </div>
      </div>

      <div class="col-md-4">
        <p><%= @user.description %></p>
      </div>
    </div>
    <h2 class="text-center">MENSAJES</h2>

    <% @messages.each do |message| %>
        <div>
            <p><%= message.author_name %></p>
            <p><%= message.body %></p>
            <p><%= message.created_at %></p>
        </div>
    <% end %>

    <% if logged_in? %>
        <%= form_for :message, url: messages_user_path do |f| %>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, class: 'form-control' %>
            </div>

            <%= f.hidden_field :author_name, value: current_user.name %>
            <%= f.hidden_field :author, value: current_user.id %>
            <%= f.hidden_field :user, value: @user.id %>

            <div class="text-center">
                <%= f.submit 'Envíar mensaje', class: 'btn btn-lg myButton' %>
            </div>
        <% end %>
      <% end %>
  </div>
</div>