config/routes.rb
Rails.application.routes.draw do

  get '/static_pages/FAQ'
  get 'people' => 'people#index'
  post 'people/filter' => 'people#filter'
  post 'users/filter' => 'users#filter'
  post 'teams/filter' => 'teams#filter'
  get 'sessions/new'
  get '/myteams' => 'teams#showbyuser'
  post 'messages' => 'messages#create'
  post 'messages/user' => 'messages#create_user_message'
  post 'addmember' => 'teams#add_user'

  resources :teams
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'home#index'

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div>
      El formulario contiene <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_team.html.erb
<% if @team.errors.any? %>
  <div id="error_explanation">
    <div>
      El formulario contiene <%= pluralize(@team.errors.count, "error") %>.
    </div>
    <ul>
      <% @team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_team.html.erb
<div class="col-md-10 team_cards">
    <div>
        <div class="col-xs-5 team pull-left"><h3><i><b><%= link_to team.teamname, team_path(team), {:class=> "enlace"} %></b></i></h3>
        <p>Fecha de creación:<%= team.created_at %></p>
        <p>Ultima actualización:<%=team.updated_at%></p>
    </div>
<div class="col-xs-5 team pull-right">
    <label class="title"><h3><i><b>JUGADORES</b></i></h3></label>
    <% team.users.each do |user| %>
    <li>
        <ul><%= link_to user.name, user_path(user), {:class=> "enlace"} %></ul>
    <%end%>
    </li>
    </div>
    
    </div>

</div>

app/views/shared/_teams.html.erb
<div id="teams-table">
  <% @teams.each do  |team| %>
      <div class="row col-xs-10 col-xs-offset-1 col-md-10 col-md-offset-1 people-row">
          <%= render partial: 'shared/team', locals: {team: team} %>
      </div>
  <% end %>
</div>

app/views/shared/_user.html.erb
<div class="col-md-4 person">
  <div class="row">
    <div class="col-xs-4 col-md-4">
    <% if user.image.nil? or user.image == "" %>
            <img src="http://www.cultura-sorda.org/wp-content/uploads/2015/02/Usuario-Vacio1-300x300.png" , height="65" width="65", class= 'center-block list-avatar'/>
        <% else %>
            <%= image_tag "#{user.image}", size: '65x65', class: 'center-block list-avatar' %>

        <% end %>
      <br />
      <p><span class="glyphicon glyphicon-envelope"></span></p>
    </div>
    <div class="col-xs-8 col-md-8 list-user-data">
            <p><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <%= link_to user.name, user_path(user), {:class=> "enlace"} %></p>
            <p><span class="list-user-item"><%= user.summoner_name %></span> </p>
            <% if user.league != nil && user.league != "Unranked"%>
            <p> <%= image_tag "#{user.league.downcase}.png", size: '30x18' %>
            <%= user.league %> - <%= user.division %></p>
            <% end %>
            <% if  user.league.nil? || user.league == "" || user.league == "Unranked"%>
              <p><span class="glyphicon glyphicon-king"></span> <%= user.league %></p>
            <% end %>
           
    </div>
  </div>
</div>

app/views/shared/_users.html.erb
<div id="users-table">
  <% @users.in_groups_of(3, false).each do  |group| %>
      <div class="row col-xs-10  col-md-10 people-row center-block">
        <% group.each do |user| %>
          <%= render partial: 'shared/user', locals: {user: user} %>
        <% end %>
      </div>
  <% end %>
</div>