config/routes.rb
Rails.application.routes.draw do

  get '/static_pages/FAQ'
  get 'people' => 'people#index'
  post 'people/filter' => 'people#filter'
  post 'users/filter' => 'users#filter'
  post 'teams/filter' => 'teams#filter'
  get 'sessions/new'
  get '/myteams' => 'teams#showbyuser'
  post 'messages' => 'messages#create'
  post 'messages/user' => 'messages#create_user_message'
  post 'addmember' => 'teams#add_user'

  resources :teams
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'home#index'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid">
    <p>
    Made with <span class="glyphicon glyphicon-heart"></span>
  </p>

    <ul class="breadcrumb">
      <li><%= link_to 'Attributions', '#' %></li>
      <li><%= link_to 'Team', '#' %></li>
      <li><%= link_to 'Blog', '#' %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<link rel="stylesheet" type="text/css" href="style.css.scss">

<header class="header">
  <nav id="navigation-menu" class=" navbar header negrita AllMayus navbar-fixed-top">
    <div class="container-fuild">
      <div class="navbar-header">
        <button class="navbar-toggle"
                aria-controls="navbar"
                data-target="#navbar-menu" data-toggle="collapse"
                type="button" aria-expanded="">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <%= link_to "LOLPremade", root_path, class: 'navbar-brand' %>
      </div>

      <div id="navbar-menu" class="collapse navbar-collapse"
           aria-expanded="false" style="hight: 1px;">
        <ul class="nav navbar-nav options-menu">
          <li class="menu-option option"><%= link_to "Usuarios", :controller => "users", :action => "index" %></li>
          <li class="menu-option option"><%= link_to "Equipos", teams_path %></li>

          <% if logged_in? %>
            <%if current_user.teams.size==0 %>
            <li class="menu-option option"><%= link_to "Mi Equipo",:controller => "teams", :action => "new" %></li>
            <%end%>
            <%if current_user.teams.size!=0 %>
            <li class="menu-option option"><%= link_to "Mis Equipos",'/myteams' %></li>
            <%end%>
            <li class="dropdown option">
              <a href="#" class="dropdown-toogle option" data-toggle="dropdown">
                Cuenta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu option">
                  <li><%= link_to 'Perfil', current_user %></li>
                <li><%= link_to 'Configuración', edit_user_path(current_user) %></li>
                <li><%= link_to "Equipos", :controller => "teams", :action => "new" %></li>
                <li class="divider"></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li class="option"><%= link_to 'Log in', login_path %></li>
          <% end %>
         <li class="menu-option option"><%= link_to 'FAQ', '/static_pages/FAQ', class: 'menu-link' %></li>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lolpremade</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="theme-color" content="#009688">
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap" class="container-fuid clear-top">
<div id="main">
  <%= render 'layouts/header' %>

  <% flash.each do |message_type, message| %>
    <div class="footer alert alert-<%= message_type %>"><%= message %></div>
  <% end %>


  <%= yield %>
</div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>